//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum NewDataTable2Names {
        
        TTT = 0,
    }
    
    [System.SerializableAttribute()]
    public class NewDataTable2 : WanFramework.Data.DataTableAsset<NewDataTable2.Entry> {
        
        public Game.Data.NewDataTable2.Entry Get(Game.Data.NewDataTable2Names id) {
            return ((Game.Data.NewDataTable2.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string name;
            
            [UnityEngine.SerializeField()]
            private Game.Data.NewDataTableNames tableRef;
            
            public string Name {
                get {
                    return this.name;
                }
            }
            
            public Game.Data.NewDataTableNames TableRef {
                get {
                    return this.tableRef;
                }
            }
        }
    }
}
