//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum NewDataTableNames {
        
        test2 = 0,
        
        test8 = 1,
        
        test3 = 2,
        
        test5 = 3,
    }
    
    [System.SerializableAttribute()]
    public class NewDataTable : WanFramework.Data.DataTableAsset<NewDataTable.Entry> {
        
        public Game.Data.NewDataTable.Entry Get(Game.Data.NewDataTableNames id) {
            return ((Game.Data.NewDataTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string name;
            
            [UnityEngine.SerializeField()]
            private string test;
            
            [UnityEngine.SerializeField()]
            private string test12;
            
            [UnityEngine.SerializeField()]
            private string test222;
            
            [UnityEngine.SerializeField()]
            private UnityEngine.GameObject prefab;
            
            [UnityEngine.SerializeField()]
            private UnityEngine.GameObject prefab2;
            
            public string Name {
                get {
                    return this.name;
                }
            }
            
            public string Test {
                get {
                    return this.test;
                }
            }
            
            public string Test12 {
                get {
                    return this.test12;
                }
            }
            
            public string Test222 {
                get {
                    return this.test222;
                }
            }
            
            public UnityEngine.GameObject Prefab {
                get {
                    return this.prefab;
                }
            }
            
            public UnityEngine.GameObject Prefab2 {
                get {
                    return this.prefab2;
                }
            }
        }
    }
}
